// Generated by https://quicktype.io

export interface ServerGrocery {
  id: string;
  image_url: string;
  stock: number;
  productName: string;
  price: number;
  productDescription: string;
  favorite: number | string;
}

export interface Grocery {
  id: string;
  imageUrl: string;
  isFavorite: boolean;
  price: number;
  productDescription: string;
  productName: string;
  stock: number;
  unitsInCart: number;
}

export const mapGroceryFromServer = (serverGrocery: ServerGrocery) => {
  let isFavorite = false;
  // TODO: fix server response to always return same type
  if (serverGrocery.favorite === 1 || serverGrocery.favorite === '1') {
    isFavorite = true;
  }

  const grocery: Grocery = {
    id: serverGrocery.id,
    imageUrl: serverGrocery.image_url,
    isFavorite,
    price: serverGrocery.price,
    productDescription: serverGrocery.productDescription,
    productName: serverGrocery.productName,
    stock: serverGrocery.stock,
    unitsInCart: 0,
  };

  return grocery;
};
