// Generated by https://quicktype.io

export interface Grocery {
  id: string;
  image_url: string; // TODO: lower camel case
  stock: number;
  productName: string;
  price: number;
  productDescription: string;
  favorite: number | string;
}
